mautic/mautic-wordpress

readme.txt
I'm going to submit this plugin to wordpress.org
=> Readme.txt for wordrpess.org updated accorging to readme.md

README.md, options.php, readme.txt, wpmautic.php
Also fix for https://github.com/mautic/mautic-wordpress/issues/4
=> URL Query data added, some UX improvements, security 

readme.txt, wpmautic.php
Also tested WP version raised to 4.3. Tested on this WP version.
=> Version raised to 1.0.1, WP readme installation updated

README.md, options.php
=> Installation via WP admin documented, improved name for base URL field

wpmautic.php
Fix to Trimmed URL with adjustments made by @escopecz too, as seen on #5
=> Fix to Trimmed URL

options.php, readme.txt
I think use `submit_button();` function to show submit button html.
This function is WordPress's function to show submit button.
https://codex.wordpress.org/Function_Reference/submit_button
=> convert submit button html to WordPress's core function

index.php, options.php, phpcs.xml, wpmautic.php
This new code style guid will help normalize source code and avoid bad file diffs.
Related to #45
=> Implement PHPCodeSniffer in the project

README.md, readme.txt, wpmautic.php
This PR add Focus shortcode to plugin:
[mautic type="focus" id="1"]
=> Add Focus Shortcode and Documentation

README.md, readme.txt, wpmautic.php
This PR add Tags shortcode to plugin: [mautic type="tags" values="mytag,anothertag,-removetag"]
=> Add Tags shortcode and Documentation

CHANGELOG.md, options.php, shortcodes.php
Make the plugin translation ready !
=> Translation ready 

CHANGELOG.md, README.md, readme.txt, tests/CustomAttributesTest.php, tests/ScriptInjectionTest.php, wpmautic.php
This function also define a filter which allow users to add specific data inside mautic trackers : `wpmautic_tracking_attributes`.
=> Add a new function `wpmautic_get_tracking_attributes`

shortcodes.php, tests/ShortCodeTest.php
Hello @shulard ... this is an little update to make gated video compatible with new mautic 2.9.1
See here https://github.com/mautic/mautic/pull/4438
Thanks @shulard
=> Compatibility gated videos 2 9 0

tests/ScriptInjectionTest.php, tests/SettingsTest.php, tests/WPMauticTestCase.php, tests/bootstrap.php
The tests on PHP master version are failing due to deprecation notice : https://travis-ci.org/mautic/mautic-wordpress/jobs/300712875
This PR handle the edge cases to allow compat with PHP7.2 which will be released very soon.
=> Prepare the plugin for PHP7.2 compatibility.

options.php, shortcodes.php, wpmautic.php
=> Admin improvements

.travis.yml
See: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment#1-services-support
=> Travis: Must explicitely declare services (mysql).

.travis.yml, CHANGELOG.md, composer.json, composer.lock, options.php, tests/OptionsTest.php, tests/OptionsValidationTest.php, tests/ScriptInjectionTest.php, tests/SettingsTest.php, wpmautic.php
This PR also introduce a new function `wpmautic_base_script` which allows to retrieve the full mautic script URL. This can be useful if you need to load the script using another way than the default one.
=> GDPR compliance, add new setting to allow disable automatic script loading.

.travis.yml, CHANGELOG.md, wpmautic.php
Also update test matrix to run tests against that new version.
=> Mark compatibility with WordPress 5.4.

options.php
Update the doc to ensure it's clear.
Related to #105
=> When using shortcodes, tracking always active.

.github/workflows/deploy.yml, .github/workflows/update.yml
This updates the Github workflow to use SLUG env.
=> Updated: Github action to use SLUG environment variable

readme.txt
=> Added: Contributor
